//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zolotoy_telenok_0._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZTDBEntities : DbContext
    {
        public ZTDBEntities()
            : base("name=ZTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Запись> Запись { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Машина> Машина { get; set; }
        public virtual DbSet<Работник> Работник { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
    }
}
