//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zolotoy_telenok_0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public int ИД_Записи { get; set; }
        public int ИД_Машины { get; set; }
        public int ИД_Работнка { get; set; }
        public int ИД_Услуги { get; set; }
        public decimal Сумма { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Машина Машина { get; set; }
        public virtual Работник Работник { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
